name: CI - Playwright

on:
  push:
    branches: ["main", "feat/**", "fix/**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [chromium]
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            server/pnpm-lock.yaml

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Install server dependencies
        run: pnpm install --frozen-lockfile --prefix server

      - name: Install Playwright Browsers
        run: pnpm --prefix server exec playwright install --with-deps ${{ matrix.project }}

      - name: Run Playwright tests (headless, workers=2)
        run: pnpm --prefix server test -- --project=${{ matrix.project }} --workers=2

      - name: Upload Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Each matrix run produces its own blob-report directory; include project in the name to avoid collisions
          name: blob-report-${{ matrix.project }}
          path: server/blob-report
          retention-days: 14

# ---------------------------------------------------------------------
# Consolidate the sharded blob reports into a single HTML report
# ---------------------------------------------------------------------

  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            server/pnpm-lock.yaml

      - name: Install server dependencies (Playwright for merge CLI)
        run: pnpm install --frozen-lockfile --prefix server

      - name: Download blob-report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          path: _blob-aggregated
          merge-multiple: true

      - name: Debug - List downloaded files
        run: |
          echo "Contents of _blob-aggregated:"
          ls -la _blob-aggregated/
          echo "Looking for blob report files:"
          find _blob-aggregated -name "*.zip" -o -name "*.json" -o -name "report.json" || echo "No blob files found"

      - name: Merge reports into HTML
        run: |
          pnpm --prefix server exec playwright merge-reports --reporter html _blob-aggregated/

      - name: Upload Merged HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14 