name: CI - Playwright

on:
  push:
    branches: ["main", "feat/**", "fix/**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [chromium]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm install --no-audit --no-fund

      - name: Install server dependencies
        run: npm install --no-audit --no-fund --prefix server

      - name: Install Playwright Browsers
        run: npx --prefix server playwright install --with-deps ${{ matrix.project }}

      - name: Run Playwright tests (headless, workers=2)
        run: npm --prefix server run test -- --project=${{ matrix.project }} --workers=2

      - name: Upload Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Each matrix run produces its own blob-report directory; include project in the name to avoid collisions
          name: blob-report-${{ matrix.project }}
          path: server/blob-report
          retention-days: 14

# ---------------------------------------------------------------------
# Consolidate the sharded blob reports into a single HTML report
# ---------------------------------------------------------------------

  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server dependencies (Playwright for merge CLI)
        run: npm install --no-audit --no-fund --prefix server

      - name: Download blob-report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          path: ./_blob-aggregated

      - name: Merge reports into HTML
        run: |
          npx --yes playwright merge-reports --reporter html _blob-aggregated/blob-report-*/*

      - name: Upload Merged HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14 